import { Routes } from '@angular/router';
import { adminGuard, adminPublicOnlyGuard, driverGuard, employerGuard, publicOnlyGuard, signedInGuard } from './core/auth.guard';

export const routes: Routes = [
  { path: '', canActivate: [publicOnlyGuard], loadComponent: () => import('./pages/home/home.page').then((m) => m.HomePage) },
  { path: 'login', canActivate: [publicOnlyGuard], loadComponent: () => import('./pages/login/login.page').then((m) => m.LoginPage) },
  { path: 'forgot-password', canActivate: [publicOnlyGuard], loadComponent: () => import('./pages/forgot-password/forgot-password.page').then((m) => m.ForgotPasswordPage) },
  { path: 'register', canActivate: [publicOnlyGuard], loadComponent: () => import('./pages/register/register.page').then((m) => m.RegisterPage) },
  { path: 'registration-success', canActivate: [signedInGuard], loadComponent: () => import('./pages/registration-success/registration-success.page').then((m) => m.RegistrationSuccessPage) },
  { path: 'settings', canActivate: [signedInGuard], loadComponent: () => import('./pages/settings/settings.page').then((m) => m.SettingsPage) },
  { path: 'support', canActivate: [signedInGuard], loadComponent: () => import('./pages/support/support.page').then((m) => m.SupportPage) },
  { path: 'book-driver', canActivate: [employerGuard], loadComponent: () => import('./pages/book-driver/book-driver.page').then((m) => m.BookDriverPage) },
  { path: 'employer', redirectTo: 'employer/dashboard', pathMatch: 'full' },
  { path: 'employer/dashboard', canActivate: [employerGuard], loadComponent: () => import('./pages/employer-dashboard/employer-dashboard.page').then((m) => m.EmployerDashboardPage) },
  { path: 'employer/chauffeurs', canActivate: [employerGuard], loadComponent: () => import('./pages/employer-chauffeurs/employer-chauffeurs.page').then((m) => m.EmployerChauffeursPage) },
  { path: 'employer/profile', canActivate: [employerGuard], loadComponent: () => import('./pages/employer-profile/employer-profile.page').then((m) => m.EmployerProfilePage) },
  { path: 'employer/profile/edit', canActivate: [employerGuard], loadComponent: () => import('./pages/employer-profile/employer-profile.page').then((m) => m.EmployerProfilePage) },
  { path: 'employer/notifications', canActivate: [employerGuard], loadComponent: () => import('./pages/notifications/notifications.page').then((m) => m.NotificationsPage) },
  { path: 'driver', redirectTo: 'driver/dashboard', pathMatch: 'full' },
  { path: 'driver/dashboard', canActivate: [driverGuard], loadComponent: () => import('./pages/driver-dashboard/driver-dashboard.page').then((m) => m.DriverDashboardPage) },
  { path: 'driver/bookings', canActivate: [driverGuard], loadComponent: () => import('./pages/driver-bookings/driver-bookings.page').then((m) => m.DriverBookingsPage) },
  { path: 'driver/earnings', canActivate: [driverGuard], loadComponent: () => import('./pages/driver-earnings/driver-earnings.page').then((m) => m.DriverEarningsPage) },
  { path: 'driver/profile', canActivate: [driverGuard], loadComponent: () => import('./pages/driver-profile/driver-profile.page').then((m) => m.DriverProfilePage) },
  { path: 'driver/profile/edit', canActivate: [driverGuard], loadComponent: () => import('./pages/driver-profile/driver-profile.page').then((m) => m.DriverProfilePage) },
  { path: 'driver/notifications', canActivate: [driverGuard], loadComponent: () => import('./pages/notifications/notifications.page').then((m) => m.NotificationsPage) },
  { path: 'admin/login', canActivate: [adminPublicOnlyGuard], loadComponent: () => import('./pages/admin-login/admin-login.page').then((m) => m.AdminLoginPage) },
  { path: 'admin', redirectTo: 'admin/dashboard', pathMatch: 'full' },
  { path: 'admin/dashboard', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-dashboard/admin-dashboard.page').then((m) => m.AdminDashboardPage) },
  { path: 'admin/profile', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-profile/admin-profile.page').then((m) => m.AdminProfilePage) },
  { path: 'admin/admins', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-admins/admin-admins.page').then((m) => m.AdminAdminsPage) },
  { path: 'admin/users', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-users/admin-users.page').then((m) => m.AdminUsersPage) },
  { path: 'admin/employers', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-employers/admin-employers.page').then((m) => m.AdminEmployersPage) },
  { path: 'admin/drivers', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-drivers/admin-drivers.page').then((m) => m.AdminDriversPage) },
  { path: 'admin/bookings', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-bookings/admin-bookings.page').then((m) => m.AdminBookingsPage) },
  { path: 'admin/callcenter', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-callcenter/admin-callcenter.page').then((m) => m.AdminCallcenterPage) },
  { path: 'admin/support', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-support/admin-support.page').then((m) => m.AdminSupportPage) },
  { path: 'admin/verification', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-verification/admin-verification.page').then((m) => m.AdminVerificationPage) },
  { path: 'admin/notifications', canActivate: [adminGuard], loadComponent: () => import('./pages/admin-notifications/admin-notifications.page').then((m) => m.AdminNotificationsPage) },
  { path: 'dashboard', redirectTo: 'employer/dashboard', pathMatch: 'full' },
  { path: '**', redirectTo: '' }
];
