import { bootstrapApplication } from '@angular/platform-browser';
import { provideRouter } from '@angular/router';
import { provideHttpClient } from '@angular/common/http';
import { provideIonicAngular } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  alertCircleOutline,
  addCircleOutline,
  arrowBackOutline,
  arrowForwardOutline,
  barChartOutline,
  briefcaseOutline,
  calendarOutline,
  cameraOutline,
  carOutline,
  carSportOutline,
  cashOutline,
  checkmarkCircle,
  checkmarkCircleOutline,
  cloudUploadOutline,
  closeOutline,
  businessOutline,
  createOutline,
  documentAttachOutline,
  documentTextOutline,
  gitBranchOutline,
  grid,
  gridOutline,
  homeOutline,
  helpCircleOutline,
  idCardOutline,
  imagesOutline,
  informationCircleOutline,
  location,
  locationOutline,
  locateOutline,
  logOutOutline,
  mapOutline,
  menuOutline,
  moonOutline,
  navigate,
  navigateOutline,
  notificationsOutline,
  notificationsOffOutline,
  personCircleOutline,
  personOutline,
  peopleOutline,
  power,
  powerOutline,
  refreshOutline,
  ribbonOutline,
  star,
  saveOutline,
  settingsOutline,
  shieldCheckmarkOutline,
  speedometerOutline,
  syncOutline,
  sunnyOutline,
  timeOutline,
  trashOutline,
  walletOutline,
} from 'ionicons/icons';
import { AppComponent } from './app/app.component';
import { routes } from './app/app.routes';

addIcons({
  alertCircleOutline,
  addCircleOutline,
  arrowBackOutline,
  arrowForwardOutline,
  barChartOutline,
  briefcaseOutline,
  calendarOutline,
  cameraOutline,
  carOutline,
  carSportOutline,
  cashOutline,
  checkmarkCircle,
  checkmarkCircleOutline,
  cloudUploadOutline,
  closeOutline,
  businessOutline,
  createOutline,
  documentAttachOutline,
  documentTextOutline,
  gitBranchOutline,
  grid,
  gridOutline,
  homeOutline,
  helpCircleOutline,
  idCardOutline,
  imagesOutline,
  informationCircleOutline,
  location,
  locationOutline,
  locateOutline,
  logOutOutline,
  mapOutline,
  menuOutline,
  moonOutline,
  navigate,
  navigateOutline,
  notificationsOutline,
  notificationsOffOutline,
  personCircleOutline,
  personOutline,
  peopleOutline,
  power,
  powerOutline,
  refreshOutline,
  ribbonOutline,
  saveOutline,
  settingsOutline,
  shieldCheckmarkOutline,
  speedometerOutline,
  star,
  syncOutline,
  sunnyOutline,
  timeOutline,
  trashOutline,
  walletOutline,
});

bootstrapApplication(AppComponent, {
  providers: [provideIonicAngular(), provideRouter(routes), provideHttpClient()]
}).catch((error) => console.error(error));
